sanity-io/get-it

package.json
src/middleware/defaultOptionsProcessor.js
src/request/browser-request.js

This fixes a couple of issues when attempting to use get-it with React Native.
React Native on Android complains about long timers, so I adjusted the default down to 60s on React Native, which seems acceptable.

React Native support

---

README.md
src/middleware/promise.js
test/promise.test.js

As outlined in #9 - allow the promise middleware to resolve only the response body. This is especially useful when paired with the `httpErrors` middleware, as you won't have to check the status code.

Allow promise middleware to only resolve response body

---

package-lock.json
package.json
src/index.js
src/request/browser-request.js
src/request/browser/fetchXhr.js
test/fetch.test.js

Certain environments (like CloudFlare workers) are browser-like, but do not have a `window` property, nor `XMLHttpRequest`. They _do_ however have the `fetch` API.
With this change, we introduce a fallback if the `XMLHttpRequest` API cannot be found, by providing a minimal(ish) implementation of the XMLHttpRequest API backed by the `fetch` API.
The bundle size difference is about 1kB in an isolated case, so not hugely significant (9% increase).
I did experiment with modernizing the library, moving it to typescript and using the fetch API as the base, but it feels like a bit too big of a change to fix this one environment issue, so I would rather do this as an intermediary step and handle a modernization effort in a separate PR.
There are a few `onX` methods being called directly on the …

feat: add fetch-based fallback

---

.github/workflows/ci.yml
modules.d.ts
package-lock.json
package.json
src/createRequester.ts
src/request/browser-request.ts
src/request/browser/fetchXhr.ts
src/util/pubsub.ts
test-deno/import_map.json
test/abort.test.ts
test/basics.test.ts
test/debug.test.ts
test/progress.test.ts
tsconfig.settings.json

We already dropped IE support by shipping more modern syntax in `get-it@8`. The IE cleanup in this PR can thus be done as a patch release.
`nano-pubsub` is inlined, for now, until it ships ESM. Just to unblock `@sanity/client`'s migration to 100% ESM.

fix: improve `fetch` fallback, drop dead IE legacy

---

middleware.js

Older tooling like jest 27 that does not support the `exports`  field of `package.json` usually also has trouble with ESM. I might be missing something (the runtime support matrix is _wild_ after all), but I think the `middleware.js` legacy export file should be using CommonJS and reexporting the CommonJS middleware file.
Let me know if this is _not_ correct.

fix: use commonjs for legacy middleware export

---

src/types.ts

Uncovered as part of https://github.com/sanity-io/client/pull/199/files

fix: add missing attemptNumber argument to retry option typings

---

test/proxy.test.ts

This PR will be rebased to check up on `tunnel-agent` and NodeJS v20. Hopefully they'll be friends again well before v20 is scheduled to be the new LTS.

chore(tests): re-enable proxy test

---

package-lock.json
package.json
src/middleware/keepAlive/node-keepAlive.ts
src/middleware/mtls.ts
src/request/browser-request.ts
src/request/browser/fetchXhr.ts
src/request/node-request.ts
src/types.ts
src/util/isBrowserOptions.ts
src/util/lowerCaseHeaders.ts
test-next/app/utils.ts
test-next/package-lock.json
test/node.fetch.test.ts

It looks like it's doable to rework everything on the `node` side of things to use `fetch` ([undici](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch)). But it'll take time. For now the goal is to do the bare minimum to allow [React Server Components](https://nextjs.org/docs/app/building-your-application/data-fetching#the-fetch-api) to benefit from [Automatic Fetch Deduping (without having to wrap all calls in `React.cache`)](https://nextjs.org/docs/app/building-your-application/data-fetching#automatic-fetch-request-deduping), as well as using infrastructure features such as the [Vercel Data Cache](https://vercel.com/docs/infrastructure/data-cache).
This PR uses an [end-to-end test](https://github.com/sanity-io/get-it/actions/runs/5395999473/jobs/9799122418) that checks …

feat: add support for `fetch` in node, and allow setting `cache` and `next` on `edge`

---

package-lock.json
package.json
test-deno/import_map.json
test-esm/test.cjs
test-esm/test.mjs

Improves build time, and reduces complexity.
It was runtime tested in native CJS and ESM in Node, by using two separate files:
`runtime.cjs`:
```js
const debug = require('debug')
const decompressResponse = require('decompress-response')
const followRedirects = require('follow-redirects')
const intoStream = require('into-stream')
const isPlainObject = require('is-plain-object')
const isRetryAllowed = require('is-retry-allowed')
const isStream = require('is-stream')
const parseHeaders = require('parse-headers')
const progressStream = require('progress-stream')
const tunnelAgent = require('tunnel-agent')
console.log({
debug,
decompressResponse,
followRedirects,
intoStream,
isPlainObject,
isRetryAllowed,
isStream,
parseHeaders,
progressStream,
tunnelAgent,
})
```
`runtime.mjs`:
```js
import …
```

fix: remove node ESM wrapper

---

src/request/browser-request.ts
src/request/browser/fetchXhr.ts
src/types.ts
test-next/app/utils.ts
test-next/package-lock.json

This is part 1 of 2 in the saga of supporting App Router fetching with [Request Memoization](https://nextjs.org/docs/app/building-your-application/caching#opting-out).
Part 2 will be in the `@sanity/client` repo.
I'm not super happy with this fix, and feel we should come back later, and as part of working on #12 we should solve this in a better way.

fix: add ability to opt-out of setting `signal` on `fetch`

---

src/middleware/defaultOptionsProcessor.ts
test/basics.test.ts

Pull up a chair.
Some React Native versions have a completely broken `URL` and `URLSearchParams` implementations. The latest issue I came across is that if you pass a URL that includes a query string to the `URL` constructor, it appends a trailing slash and has an empty `searchParams` property.
This creates problems when you also pass a `query` option to the request, which should append those query parameters to the existing URLs. Because the parsed URL has an empty `searchParams`, it will append the new query parameters to an empty object and then encode it, resulting in a URL without the original query parameters.
In other words:
```tsx
request({
url: 'https://foo.bar/some/path?myQuery=string',
query: {appendThis: 'forMe'}
})
```
Will result in:
- React Native: …

fix: query string merging in legacy react native versions

---

src/middleware/defaultOptionsProcessor.ts
test/basics.test.ts

Reverts sanity-io/get-it#351 as it creates a regression reported here: https://github.com/sanity-io/client/issues/641
and reproduced here: https://github.com/sanity-io/client-runtimes-compatibility/commit/0d31fbe879c909a3e5f28aa4d20c1150f7a1b4bd#diff-75779b1f60b3c3d7a086000e17965494eeb3d3d1c53f0806a3be1538fce55048

fix: Revert "fix: query string merging in legacy react native versions"

---

.github/workflows/ci.yml
package.json

Lifted this from 4eaa5079ea2c87c5fbda1b100895b597bfd3765b as it seemed unrelated to the actual change - figure this is still helpful for preleases for now?

ci: move npm config provenance flag to ci workflow

---

src/middleware/defaultOptionsProcessor.ts

React Native has a new release out, which implements `.set()` on `URLSearchParams`, but does _not_ implement the ability to pass a string to the constructor. Thus, the previous check broke.
Getting tired of keeping these checks in line, so I figure we may as well just blindly use the dumbest query string behavior for React Native, based on navigator check.

fix: react native query string parsing

---

package-lock.json
package.json
src/request/node-request.ts
test-deno/import_map.json
test/json.test.ts
test/stream.test.ts
test/urlEncoded.test.ts

Removes the `into-stream` in favor of node's `Readable.from` method. Additionally removes `is-stream` because it's implementation is so easily inlinable.
This is regarding [SDX-1326](https://linear.app/sanity/issue/SDX-1326/[cli]-json-body-serialization-when-using-sanity-dataset-import-command).
It seems like there are certain cases where get-it would only send part of the request to the server resulting in the server sending a 400 with an `unexpected EOF` error. It took me a while to find but I've traced it back to this old version of `into-stream`.
Research:
- We currently using `into-stream` v6 which seems to unnecessarily slow down transmission by [splitting up the body into arbitrary chunks??](https://github.com/sindresorhus/into-stream/blob/4e07b9f4f84e59de83f2d6b246d945b3f2362ded/in …

feat: improved request body stream conversion

---

.github/workflows/ci.yml

ci: don't test on Node 16 anymore

---

src/middleware/keepAlive.ts
test/keepAlive.test.ts

This actually fixes two things:
- We incorrectly did "throw err" instead of "return err". This causes the request to stall and return any error or response.
- We also weren't respecting `maxRetries: 0`. I discovered this because I wanted to reproduce the problem above.

fix(keep-alive): correctly handle error

---

src/request/node-request.ts
src/request/node/timedOut.ts
test/socket.test.ts

Since keep alive keeps the socket around for a longer time, we end up keep adding emitters to the socket since onError is only called if the socket errors. This makes sure we are cleaning up when the response is completed.
Fixes sanity-io/get-it#488

fix(node): fix eventemitter leak when checking for broken socket

---

package-lock.json
package.config.ts
package.json

The change introduced in https://github.com/sanity-io/get-it/commit/18798b607c2a10d07efcb6fee48719b881e891ae causes issues with Next.js repos that also have a custom babel setup (typically by adding a `.babelrc` or `babel.config.js` in the root):
```bash
Attempted import error: 'retry' is not exported from 'get-it/middleware' (imported as 'retry').
```
The reason for this error is this code (from `get-it/dist/middleware.browser.js`, which is the inlined source from `debug`):
```js
var common = setup;
(function (module, exports) {
/* ... other exports */
exports.log = console.debug || console.log || (() => {});
module.exports = common(exports);
})(browser, browser.exports);
```
The `module.exports` reference isn't supported by `next` when it occurs in a ESM file, even though it's inline …

fix: regression where inlining `debug` breaks next.js envs on custom babel

---

src/request/node-request.ts
src/request/node/proxy.ts
src/types.ts
test/proxy.test.ts

4 years ago, https://github.com/sanity-io/sanity/pull/2661 introduced a change in the `@sanity/client` where the `proxy` request option would always be set - either to an actual value, or to `undefined`. This broke automatic proxying in the client through environment variables (`HTTPS_PROXY` etc) because get-it used an overly pedantic `hasOwnProperty` check instead of checking for some not undefined value.
With this change, we instead automatically infer the proxy if the `proxy` option is either not present, **OR** it is `undefined`. Users can still opt out by setting it to `null` or `false` explicitly.
Also improves on the typescript coverage.

fix: auto-infer proxy if `proxy` option is `undefined`
